sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.4.0"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install polygonal-ds
  - haxelib install utest

script:
  - haxe tests.hxml
